import Foundation
import StoreKit

struct FabushiPayReceipt: Decodable, Sendable {
    let paymentId: String
    let sku: String
    let rail: String
    let amount: Int64
    let currency: String
    let status: String
}

enum FabushiPayStoreKitError: LocalizedError, Sendable {
    case invalidPaymentIdentifier
    case productUnavailable
    case advancedCommerceUnavailable
    case unverifiedTransaction
    case transactionAccountMismatch
    case pending
    case userCancelled
    case noRestorablePurchase
    case invalidServerResponse
    case serverRejected(Int, String)

    var errorDescription: String? {
        switch self {
        case .invalidPaymentIdentifier: return "支付订单标识无效"
        case .productUnavailable: return "App Store 商品暂不可用"
        case .advancedCommerceUnavailable: return "当前 iOS / App Store 环境不支持 Advanced Commerce"
        case .unverifiedTransaction: return "App Store 交易验证失败"
        case .transactionAccountMismatch: return "App Store 交易不属于当前支付订单"
        case .pending: return "支付正在等待 App Store 确认"
        case .userCancelled: return "用户取消了支付"
        case .noRestorablePurchase: return "当前 App Store 账号没有可恢复的买断交易"
        case .invalidServerResponse: return "支付服务器返回了无效响应"
        case .serverRejected(let status, let message): return "支付服务器拒绝交易（\(status)）：\(message)"
        }
    }
}

/// Native StoreKit 2 adapter for Fabushi Pay.
///
/// `paymentId` is a UUID generated by the trusted Rust payment service. It is
/// sent to Apple as `appAccountToken`, so the App Store returns the same token
/// in the transaction and the backend can bind a transaction to exactly one
/// Payment Intent before granting an entitlement.
actor FabushiPayStoreKit {
    typealias AccessTokenProvider = @MainActor @Sendable () async throws -> String

    private let serviceBaseURL: URL
    private let accessTokenProvider: AccessTokenProvider
    private let session: URLSession

    init(
        serviceBaseURL: URL = URL(string: "https://pay.ombhrum.com")!,
        session: URLSession = .shared,
        accessTokenProvider: @escaping AccessTokenProvider
    ) {
        self.serviceBaseURL = serviceBaseURL
        self.session = session
        self.accessTokenProvider = accessTokenProvider
    }

    func purchase(
        paymentId: String,
        productId: String,
        verifyPath: String
    ) async throws -> FabushiPayReceipt {
        guard let appAccountToken = UUID(uuidString: paymentId) else {
            throw FabushiPayStoreKitError.invalidPaymentIdentifier
        }
        guard let product = try await Product.products(for: [productId]).first else {
            throw FabushiPayStoreKitError.productUnavailable
        }

        let result = try await product.purchase(options: [.appAccountToken(appAccountToken)])
        switch result {
        case .success(let verification):
            guard case .verified(let transaction) = verification else {
                throw FabushiPayStoreKitError.unverifiedTransaction
            }
            guard transaction.appAccountToken == appAccountToken else {
                throw FabushiPayStoreKitError.transactionAccountMismatch
            }
            let receipt = try await verifyWithFabushiPay(
                path: verifyPath,
                transactionId: String(transaction.id)
            )
            guard receipt.paymentId == paymentId, receipt.status == "succeeded" else {
                throw FabushiPayStoreKitError.invalidServerResponse
            }
            await transaction.finish()
            return receipt
        case .pending:
            throw FabushiPayStoreKitError.pending
        case .userCancelled:
            throw FabushiPayStoreKitError.userCancelled
        @unknown default:
            throw FabushiPayStoreKitError.invalidServerResponse
        }
    }

    func purchaseAdvancedCommerce(
        paymentId: String,
        genericProductId: String,
        compactJWS: String,
        verifyPath: String
    ) async throws -> FabushiPayReceipt {
        guard #available(iOS 18.4, *) else {
            throw FabushiPayStoreKitError.advancedCommerceUnavailable
        }
        guard UUID(uuidString: paymentId) != nil, !compactJWS.isEmpty else {
            throw FabushiPayStoreKitError.invalidPaymentIdentifier
        }
        guard let product = try await Product.products(for: [genericProductId]).first else {
            throw FabushiPayStoreKitError.productUnavailable
        }
        let advancedCommerceRequestData = try Self.advancedCommerceRequestData(compactJWS: compactJWS)
        let result = try await product.purchase(options: [
            .custom(key: "advancedCommerceData", value: advancedCommerceRequestData)
        ])
        switch result {
        case .success(let verification):
            guard case .verified(let transaction) = verification else {
                throw FabushiPayStoreKitError.unverifiedTransaction
            }
            guard transaction.appAccountToken?.uuidString.lowercased() == paymentId.lowercased() else {
                throw FabushiPayStoreKitError.transactionAccountMismatch
            }
            let receipt = try await verifyWithFabushiPay(
                path: verifyPath,
                transactionId: String(transaction.id)
            )
            guard receipt.paymentId.lowercased() == paymentId.lowercased(), receipt.status == "succeeded" else {
                throw FabushiPayStoreKitError.invalidServerResponse
            }
            await transaction.finish()
            return receipt
        case .pending:
            throw FabushiPayStoreKitError.pending
        case .userCancelled:
            throw FabushiPayStoreKitError.userCancelled
        @unknown default:
            throw FabushiPayStoreKitError.invalidServerResponse
        }
    }

    /// User-initiated StoreKit restore. The original Fabushi Pay `paymentId`
    /// comes back as `appAccountToken`; each candidate is re-verified against
    /// the current Fabushi account before a durable entitlement is trusted.
    func restore(expectedSku: String) async throws -> FabushiPayReceipt {
        try await AppStore.sync()
        var deferredError: Error?
        for await verification in Transaction.currentEntitlements {
            guard case .verified(let transaction) = verification,
                  let appAccountToken = transaction.appAccountToken
            else { continue }
            let paymentId = appAccountToken.uuidString.lowercased()
            do {
                let receipt = try await verifyWithFabushiPay(
                    path: "/v1/pay/intents/\(paymentId)/apple/verify",
                    transactionId: String(transaction.id)
                )
                guard receipt.paymentId.lowercased() == paymentId,
                      receipt.status == "succeeded"
                else { throw FabushiPayStoreKitError.invalidServerResponse }
                guard receipt.sku == expectedSku else { continue }
                await transaction.finish()
                return receipt
            } catch let error as FabushiPayStoreKitError {
                if case .serverRejected(let status, _) = error, status == 403 || status == 404 {
                    continue
                }
                deferredError = error
            } catch {
                deferredError = error
            }
        }
        if let deferredError { throw deferredError }
        throw FabushiPayStoreKitError.noRestorablePurchase
    }

    static func advancedCommerceRequestData(compactJWS: String) throws -> Data {
        guard !compactJWS.isEmpty else { throw FabushiPayStoreKitError.invalidServerResponse }
        return try JSONSerialization.data(withJSONObject: [
            "signatureInfo": ["token": compactJWS]
        ], options: [.sortedKeys])
    }

    private func verifyWithFabushiPay(
        path: String,
        transactionId: String
    ) async throws -> FabushiPayReceipt {
        guard let endpoint = URL(string: path, relativeTo: serviceBaseURL)?.absoluteURL else {
            throw FabushiPayStoreKitError.invalidServerResponse
        }
        let token = try await accessTokenProvider()
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try JSONSerialization.data(withJSONObject: [
            "transactionId": transactionId
        ])

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw FabushiPayStoreKitError.invalidServerResponse
        }
        guard (200..<300).contains(http.statusCode) else {
            let message = String(data: data, encoding: .utf8) ?? "unknown payment error"
            throw FabushiPayStoreKitError.serverRejected(http.statusCode, String(message.prefix(800)))
        }
        do {
            return try JSONDecoder().decode(FabushiPayReceipt.self, from: data)
        } catch {
            throw FabushiPayStoreKitError.invalidServerResponse
        }
    }
}
